# ip:port
serverIp: 127.0.0.1:8080

spring:
  application:
    name: demo
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    name: sanqiu
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/livable?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
  messages:
    encoding: UTF-8
    basename: i18n/abt_messages
    use-code-as-default-message: true


  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    timeout: 1000
    pool:
    jedis:
      pool:
        max-idle: 8
        max-wait:
        min-idle: 0

  kafka:
      bootstrap-servers: 127.0.0.1:9092
  #指定默认topic id
      template.default-topic: house
  #指定listener 容器中的线程数，用于提高并发量
      listener:
        concurrency: 3
        #指定默认消费者group id
      consumer:
        group-id: livable
  mvc:
    static-path-pattern: /**


#  thymeleaf:
#    prefix: classpath:/templates/
##    suffix: .html
#    mode: HTML
#    encoding: UTF-8
#    cache: false
#    servlet:
#      content-type: text/html


sever:
  servlet:
    session:
      timeout: 2592000

mybatis:
  basepackage: com.qiu.demo.mapper
  mapper-locations: ["classpath*:mapper/**/*.xml"]
  type-aliases-package: com.qiu.demo.RedisBase
  mappers: com.qiu.demo.base.mapper.BaseMapper
  identity: MYSQL

logging:
  path:  C:/Users/叶三秋/Desktop/代码/livable/
  file: livable%d+%i.log
  level:
    com.chuangshu.tucheng.mapper: DEBUG



  security:
    basic:
      enabled: false
  management:
    security:
      enabled: false
