# ip:port
#serverIp: 47.106.247.251:8081
serverIp: 127.0.0.1:8081


spring:
  application:
    name: livable
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  datasource:
    name: livable
    url: jdbc:mysql://114.115.156.4:${MYSQL_PORT:3306}/livable?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.xml
  messages:
    encoding: UTF-8
    basename: i18n/abt_messages
    use-code-as-default-message: true

  redis:
    host: 47.107.137.51
    password:
    port: 6379
    database: 0
    timeout: 1000
    pool:
      max-active: 8
      max-wait: -1
      min-idle: 0
      max-idle: 8
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    #指定默认topic id
    template.default-topic: house
    #指定listener 容器中的线程数，用于提高并发量
    listener:
      concurrency: 5
      #指定默认消费者group id
    consumer:
      group-id: livable
      enable-auto-commit: false
      properties:
        session.timeout.ms: 15000
        max_poll_interval_ms: 300000
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML
#    encoding: UTF-8
#    cache: false
#    servlet:
#      content-type: text/html

#  mvc:
#    static-path-pattern: /**



sever:
  servlet:
    session:
      timeout: 2592000

mybatis:
  basepackage: com.chuangshu.livable.mapper
  mapper-locations: ["classpath*:mapper/**/*.xml"]
  type-aliases-package: com.chuangshu.RedisBase
  mappers: com.chuangshu.livable.base.mapper.BaseMapper
  identity: MYSQL

logging:
  level:
    com.chuangshu.livable.mapper: DEBUG
server:
  port: 8001